
 const families = [
  'Aref Ruqaa',
  'Asul',
  'Balthazar',
  'Cinzel',
  'Cinzel Decorative',
  'Cormorant',
  'Cormorant Garamond',
  'Cormorant Infant',
  'Cormorant SC',
  'Cormorant Unicase',
  'Cormorant Upright',
  'Fanwood',
  'Fanwood Italic',
  'Fanwood Text',
  'Fanwood Text Italic',
  'Fondamento',
  'Forum',
  'Goudy Bookletter 1911',
  'Goudy Old Style',
  'Goudy Sorts Mills',
  'Sorts Mills Goudy',
  'Goudy Sorts Mills Italic',
  'IM Fell English',
  'IM Fell French Canon',
  'IM Fell French Canon SC',
  'IM Fell Great Primer SC',
  'IM Fell Great Primer',
  'IM Fell English SC',
  'Lancelot',
  'Lato',
  'Libre Franklin',
  'Libre Baskerville',
  'Linden Hill',
   'Linden Hill Italic',
  'Marcellus',
  'Marcellus SC',
  'Merriweather',
  'Merriweather Sans',
  'Metamorphous',
  'Mirza',
  'Modern Antiqua',
  'Montaga',
  'Neuton',
  'Playfair Display',
  'Playfair Display SC',
  'Prociono',
  'Rosarivo',
  'Vesper Libre',
  'Born',
  'Butler',
  'Campton-Light',
  'League-Gothic',
  'White-Pine',
];


const webfonts = "https://fonts.googleapis.com/css?family=Aref+Ruqaa|Asul|Balthazar|Cinzel|Cinzel+Decorative|Cormorant|Cormorant+Garamond|Cormorant+Infant|Cormorant+SC|Cormorant+Unicase|Cormorant+Upright|Fondamento|Forum|IM+Fell+English|IM+Fell+English+SC|IM+Fell+French+Canon|IM+Fell+French+Canon+SC|IM+Fell+Great+Primer|IM+Fell+Great+Primer+SC|Lancelot|Lato|Libre+Baskerville|Libre+Franklin|Marcellus|Marcellus+SC|Merriweather|Merriweather+Sans|Metamorphous|Mirza|Modern+Antiqua|Montaga|Neuton|Playfair+Display|Playfair+Display+SC|Rosarivo|Sorts+Mill+Goudy|Vesper+Libre";

exports.families = families;
exports.webfonts = webfonts
